server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.10mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.10
        database: product
        auto-index-creation: true